#!/bin/sh
#
# Stringline installer.
#
# Generates a .env with real secrets, brings the stack up, and prints the setup
# code you need to claim the instance. Safe to read before running — it writes
# one file and starts two containers.
#
# Run it from the directory holding docker-compose.yml:
#
#   sh ops/install.sh
#
# Non-interactive, for an automated deploy:
#
#   STRINGLINE_URL=https://example.com BASE_PATH=/api sh ops/install.sh --yes

set -eu

ASSUME_YES=no
[ "${1:-}" = "--yes" ] && ASSUME_YES=yes

say() { printf '%s\n' "$*"; }
ask() {
    # $1 prompt, $2 default. Honours the default without prompting under --yes,
    # so the same script serves an interactive install and a scripted one.
    if [ "$ASSUME_YES" = yes ]; then printf '%s' "$2"; return; fi
    printf '%s [%s]: ' "$1" "$2" > /dev/tty
    read -r reply < /dev/tty || reply=
    printf '%s' "${reply:-$2}"
}

cd "$(dirname "$0")/.."

[ -f docker-compose.yml ] || {
    say "No docker-compose.yml here. Run this from the Stringline directory."
    exit 1
}

# Never clobber an existing .env. Regenerating JWT_SECRET signs everyone out,
# and regenerating POSTGRES_PASSWORD locks the API out of its own database
# while leaving the data perfectly intact and unreachable.
if [ -f .env ]; then
    say ""
    say "A .env already exists, so this instance is configured."
    say "Delete it deliberately if you really mean to start over — regenerating"
    say "POSTGRES_PASSWORD will lock the API out of the existing database."
    say ""
    say "Already installed? The setup code is in the log:"
    say "  docker compose logs api | grep -A2 'setup code'"
    exit 1
fi

for tool in docker openssl; do
    command -v "$tool" >/dev/null 2>&1 || { say "Need $tool on PATH."; exit 1; }
done

say ""
say "  Stringline — install"
say "  ────────────────────"
say ""

URL=$(ask "Public URL this will be served from" "${STRINGLINE_URL:-http://localhost:5173}")
BASE=$(ask "Path the API mounts at" "${BASE_PATH:-/stringline/api}")

# POSTGRES_PASSWORD must be hex, not base64. It is interpolated into a
# postgresql://user:PASSWORD@host/db URL, and base64 emits '/', '+' and '=',
# which break URL parsing — surfacing much later as a confusing auth failure at
# boot rather than an error here.
umask 077
cat > .env <<EOF
# Generated by ops/install.sh on $(date -u '+%Y-%m-%d %H:%M:%SZ').
# Keep this file. Losing JWT_SECRET signs everyone out; losing
# POSTGRES_PASSWORD locks the API out of its own database.

JWT_SECRET=$(openssl rand -base64 32)

# Hex deliberately — see the comment in ops/install.sh.
POSTGRES_PASSWORD=$(openssl rand -hex 24)

BASE_PATH=$BASE
CORS_ORIGIN=$URL
EOF
chmod 600 .env
say ""
say "  wrote .env (chmod 600)"

say "  starting containers…"
docker compose up -d --build

# The API runs migrations at boot and only then knows whether setup is pending,
# so the code cannot be printed before it is listening.
say "  waiting for the API…"
i=0
while [ $i -lt 90 ]; do
    docker compose logs api 2>/dev/null | grep -q 'listening on' && break
    sleep 2
    i=$((i + 2))
done

TOKEN=$(docker compose logs api 2>/dev/null | sed -n 's/.*│ *\([A-Za-z0-9_-]\{16\}\) *│.*/\1/p' | tail -1)

say ""
if [ -n "$TOKEN" ]; then
    say "  ────────────────────────────────────────────"
    say "  Open $URL and enter this setup code:"
    say ""
    say "      $TOKEN"
    say ""
    say "  It stops working once the first company exists."
    say "  ────────────────────────────────────────────"
else
    say "  Could not read the setup code from the log. Find it with:"
    say "    docker compose logs api | grep -B2 -A6 'no accounts yet'"
    say ""
    say "  If the API never came up:"
    say "    docker compose logs api"
fi
say ""
